[WIP] add sentry
requiemofthesouls/pigeomail pull request #23
Opened 2022-01-26 08:27 UTC by arvryna

* Fixes: https://github.com/requiemofthesouls/pigeomail/issues/17

2022-01-26 13:10 UTC, arvryna commented on monitoring/sentry.go
> +	// TODO: Need help in unmarshalling this config properly
@requiemofthesouls : Need your help here

2022-01-27 09:17 UTC, requiemofthesouls requested changes

2022-01-27 09:17 UTC, requiemofthesouls commented on monitoring/sentry.go
> +	// TODO: Need help in unmarshalling this config properly
lets make a call on Saturday then

2022-02-01 06:48 UTC, requiemofthesouls requested changes
need to pull actual master

2022-02-01 06:49 UTC, arvryna commented
this PR will be closed, will raise a different PR today

2022-02-01 06:49 UTC, closed without merging